version: '3.1'
##sets up drupal with default postgres user
services:

  drupal:
    build:
      context: .
      dockerfile: drupal.Dockerfile
    image: custom-drupal
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    restart: always
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    restart: always
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: